# See https://community.algolia.com/jekyll-algolia/github-pages.html
# This file should be at the root of your project
language: ruby
cache: bundler
script:
  - bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4

# Try to fix json (1.8.3) installation error; https://stackoverflow.com/a/32495789/5193830
before_install:
  - sudo apt-get install --yes libgmp-dev
  - bundle update nokogiri

# Turn off email notifications entirely
notifications:
  email: false